name: Cache COW (copy on write)
description: |
  Caches filesystem changes... or tries to.

inputs:
  run:
    required: true
    description: The shell script to run and cache its activity.

runs:
  using: node20
  main: dist/index.js
