name: Cache COW (copy on write)
description: |
  Caches filesystem changes... or tries to.

inputs:
  run:
    required: true
    description: The shell script to run and cache its activity.

runs:
  using: composite
  steps:
  - name: Compute cache key
    id: key
    shell: bash
    run: |
      hash="$(echo "${{ inputs.run }}" | sha256sum | cut -f 1 -d ' ')"
      echo "hash=${hash}" >> $GITHUB_OUTPUT

  - name: Restore cache
    uses: actions/cache/restore@v4
    id: cache
    with:
      path: /var/cache/cow.tar.gz
      key: cache-cow-${{ steps.key.outputs.hash }}
  
  - name: "Run, you fools!"
    if: ${{ steps.cache.outputs.cache-hit != 'true' }}
    shell: bash
    run: |
      sudo sh -x ${{ github.action_path }}/overlay.sh <<RUN_EOF
      cat /etc/resolv.conf
      cat /etc/nsswitch.conf
      host google.com

      echo ----

      ${{ inputs.run }}
      RUN_EOF

  - name: "Cache COW explodes"
    shell: bash
    run: |
      tar -zxf /var/cache/cow.tar.gz -C /

  - name: Save to cache
    uses: actions/cache/save@v4
    if: ${{ steps.cache.outputs.cache-hit != 'true' }}
    with:
      path: /var/cache/cow.tar.gz
      key: ${{ steps.cache.outputs.cache-primary-key }}

  - name: "Look at him now disappearing the cow!"
    shell: bash
    run: |
      rm /var/cache/cow.tar.gz
