name: Publish
description: Publish packages to github

inputs:
  GPG_PRIVATE_KEY:
    required: true
    description: "The gpg private key, in armored format, to use for signing packages and repositories"

runs:
  using: composite
  steps:
    - name: testing secrets
      shell: bash
      run: |
        echo "${{ inputs.GPG_PRIVATE_KEY }}"