name: Cache APT operations
inputs:
  packages:
    required: true
    type: string

runs:
  using: composite
  steps:
  - name: Restore cache
    uses: actions/cache/restore@v4
    id: apt-cache
    with:
      # Excluding patterns behave kinda weird...
      # https://github.com/actions/toolkit/issues/713#issuecomment-1030643364
      path: |
        /var/cache/apt/archives/*.deb
        /var/cache/apt/srcpkgcache.bin
        /var/cache/apt/pkgcache.bin
        /var/lib/apt/lists/*InRelease*
        /var/lib/apt/lists/*Packages*
      key: ${{ runner.os }}-apt-cache

  - name: apt-get, downloading only
    if: ${{ steps.apt-cache.outputs.cache-hit != 'true' }}
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install --download-only ${{ inputs.packages }}

      echo "BEGIN APT FILES"
      find /var/lib/apt/lists -maxdepth 1
      echo "END APT FILES"

  - name: Save to cache
    uses: actions/cache/save@v4
    if: ${{ steps.apt-cache.outputs.cache-hit != 'true' }}
    with:
      # Excluding patterns behave kinda weird...
      # https://github.com/actions/toolkit/issues/713#issuecomment-1030643364
      path: |
        /var/cache/apt/archives/*.deb
        /var/cache/apt/srcpkgcache.bin
        /var/cache/apt/pkgcache.bin
        /var/lib/apt/lists/*InRelease*
        /var/lib/apt/lists/*Packages*
      key: ${{ steps.apt-cache.outputs.cache-primary-key }}

  # https://github.com/actions/runner-images/issues/10977
  - name: Disable man-db trigger for better install speed
    shell: bash
    run: |
      echo "set man-db/auto-update false" | debconf-communicate
      dpkg-reconfigure man-db < /dev/null || true

  - name: apt-get install ${{ inputs.packages }}
    shell: bash
    run: |
      time sudo apt-get install ${{ inputs.packages }}