name: Cache APT operations
inputs:
  packages:
    required: true
    type: string

runs:
  using: composite
  steps:
  - name: Tweak permissions temporarily so that cache restore works
    shell: bash
    run: |
      id=$(whoami)
      sudo chown ${id} /var/cache/apt/archives
      sudo chown ${id} /var/lib/apt/lists
  
  - name: Compute cache key
    id: key
    shell: bash
    run: |
      hash="$(echo "${{ inputs.packages }}" | fmt -1 | sort | tr '\n' ' ' | sha256sum | cut -f 1 -d ' ')"

      echo "hash=${hash}" >> $GITHUB_OUTPUT

  - name: Restore cache
    uses: actions/cache/restore@v4
    id: apt-cache
    with:
      # Excluding patterns behave kinda weird...
      # https://github.com/actions/toolkit/issues/713#issuecomment-1030643364
      path: |
        /var/cache/apt/archives/*.deb
        /var/lib/apt/lists/*InRelease*
        /var/lib/apt/lists/*Packages*
      key: apt-cache-${{ steps.key.outputs.hash }}
  
  - name: Revert permissions change
    shell: bash
    run: |
      sudo chown root /var/cache/apt/archives
      sudo chown root /var/lib/apt/lists

  - name: apt-get, downloading only
    if: ${{ steps.apt-cache.outputs.cache-hit != 'true' }}
    shell: bash
    run: |
      time sudo apt-get update
      time sudo apt-get install --download-only ${{ inputs.packages }}

  - name: Save to cache
    uses: actions/cache/save@v4
    if: ${{ steps.apt-cache.outputs.cache-hit != 'true' }}
    with:
      # Excluding patterns behave kinda weird...
      # https://github.com/actions/toolkit/issues/713#issuecomment-1030643364
      path: |
        /var/cache/apt/archives/*.deb
        /var/lib/apt/lists/*InRelease*
        /var/lib/apt/lists/*Packages*
      key: ${{ steps.apt-cache.outputs.cache-primary-key }}

  # https://github.com/actions/runner-images/issues/10977
  - name: Disable man-db trigger for better install speed
    shell: bash
    run: |
      echo "set man-db/auto-update false" | sudo debconf-communicate
      sudo dpkg-reconfigure man-db < /dev/null || true

  - name: apt-get install ${{ inputs.packages }}
    shell: bash
    run: |
      time sudo apt-get install ${{ inputs.packages }}