name: Cache APT operations

on:
  workflow_call:
    inputs:
      packages:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache/restore@v4
      id: apt-cache
      with:
        path: |
          /var/cache/apt/archives/*.deb
          /var/cache/apt/srcpkgcache.bin
          /var/cache/apt/pkgcache.bin
          /var/lib/apt/lists
        key: ${{ runner.os }}-apt-cache

    - name: prepare the cache
      if: steps.apt-cache.outputs.cache-hit != 'true'
      run: |
        apt-get update
        apt-get install --download-only ${{ inputs.packages }}

    - uses: actions/cache/save@v4
      if: steps.apt-cache.outputs.cache-hit != 'true'
      with:
        path: |
          /var/cache/apt/archives/*.deb
          /var/cache/apt/srcpkgcache.bin
          /var/cache/apt/pkgcache.bin
          /var/lib/apt/lists
        key: ${{ steps.apt-cache.outputs.cache-primary-key }}

    - name: actually do the install
      run: |
        time apt-get install ${{ inputs.packages }}