name: APT Cache Demo

on:
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/cache-apt.yml
    with:
      packages:
        zsh tmux ruby

  example:
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout repository
        #uses: actions/checkout@v4

      - name: Try something
        run: |
          zsh --version
          tmux --version
          ruby --version