name: Ruby - Docker image

on:
  workflow_dispatch:

env:
  RUBY_VERSION: "3.4.5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ruby-build --tag ruby-build:${RUBY_VERSION}
