name: Generate Website (jekyll parts)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/actions/generate-website.yml
      - repo/website.sh
      - html

env:
  registry: ghcr.io

jobs:
  publish:
    permissions:
      # Allow this job to write to the pages branch
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: pages
          path: pages

      - uses: actions/checkout@v4
        with:
          path: code

      - name: Generate Website
        run: sh code/repo/website.sh ./code/html ./pages

      - name: Commit and push
        working-directory: pages
        run: |
          # Need to set git user and email
          # Citation> https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git status
          git commit -m "run jekyll"
          git push