name: Makefile CI

on:
  workflow_dispatch:
    inputs:
      run:
        default: echo ok

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: env | sort
      env: 
        inputs: ${{ toJSON(inputs.*) }}
