name: matrix demo

on:
  workflow_dispatch:

jobs:
  demo:
    name: Demo
    runs-on: ubuntu-latest

    strategy:
      matrix:
        foo: [ one, two, three ]

    outputs:
      data: ${{ toJSON(steps.setter.outputs.*) }}
      job-${{ strategy.job-index }}: ${{ toJSON(steps.setter.outputs.*) }}

    steps:
      - name: "Go: ${{ matrix.foo }}"
        id: setter
        run: |
          echo "foo-${{ strategy.job-index }}=${{ matrix.foo }}"
  
  summary:
    needs: [ demo ]
    name: summary
    runs-on: ubuntu-latest

    steps:
      - name: summary
        run: |
          echo "Demo outputs"
          echo "${{ toJSON(needs.demo.outputs) }}"

