name: Mess with cache

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - name: Hoodwink
        run: |
          sudo ln -s / /whoa

      - id: cachekey
        run: |
          echo "cachekey=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Cache
        id: cache-it
        uses: actions/cache@v4
        with:
          path: /whoa
          key: ${{ runner.os }}-${{ steps.cachekey.outputs.cachekey }}

      - name: Generate
        if: steps.cache-it.outputs.cache-hit != 'true'
        run: |
          sudo rm -f /whoa
          sudo mkdir -p /whoa/usr/bin
          echo "echo 'Hello world'" > sudo tee /whoa/usr/bin/hello.sh
          sudo rsync -av /whoa/ /

      - name: Try it.
        run: |
          ls -ld /whoa
          ls -ld /whoa/usr/bin/hello.sh
          ls -ld /usr/bin/hello.sh

          sh /usr/bin/hello.sh
