name: Overlay Self?
on:
  workflow_dispatch:

jobs:
  system-info:
    runs-on: ubuntu-latest

    steps:
      - name: Overlay
        run: |
          #!/bin/sh
          base=/opt/_overlay

          volume_args=""

          for path in /etc /usr /var/lib ; do
            name="$(echo $path | tr -d /)"
            overpath="${base}/${name}"

            mkdir -p "${overpath}"/work
            mkdir -p "${overpath}"/upper
            mkdir -p "${overpath}"/_

            echo ":> Creating overlay mount for $path (mounted to ${overpath}/_)"
            sudo mount -t overlay overlay -o "lowerdir=${path},upperdir=${overpath}/upper,workdir=${overpath}/work" "${overpath}/_"

            volume_args="${volume_args} --volume ${overpath}/_:${path}"
          done

          echo ":> Volume args: $volume_args"
          sudo docker run --name lol --privileged -i $volume_args ubuntu:24.04 sh << EOF
            mount | grep "^overlay"
            apt-get update
            apt-get install -y --download-only python3-django
          EOF

          #find "${base}" -type f
          sudo umount "${base}/etc/_"
          sudo umount "${base}/usr/_"
          sudo umount "${base}/varlib/_"

          sudo rsync -av "${base}/varlib/upper/" /var/lib

          # Did it make it to the host?
          dpkg -l python3-django


          # docker container export ...
          # extract /etc, /usr, and specific /var paths like /var/lib/dpkg
