name: Overlay Self?
on:
  workflow_dispatch:

jobs:
  cowtime:
    runs-on: ubuntu-latest

    steps:
      - name: Overlay
        run: |
          #!/bin/sh
          base=/opt/_overlay

          volume_args=""

          for path in /etc /usr /var/lib ; do
            name="$(echo $path | tr -d /)"
            overpath="${base}/${name}"

            mkdir -p "${overpath}"/work
            mkdir -p "${overpath}"/upper
            mkdir -p "${overpath}"/_

            echo ":> Creating overlay mount for $path (mounted to ${overpath}/_)"
            sudo mount -t overlay overlay -o "lowerdir=${path},upperdir=${overpath}/upper,workdir=${overpath}/work" "${overpath}/_"

            volume_args="${volume_args} --volume ${overpath}/_:${path}"
          done

          echo ":> Volume args: $volume_args"
          sudo docker run --name lol --privileged -i $volume_args ubuntu:24.04 sh << EOF
            mount | grep "^overlay"
            #echo "set man-db/auto-update false" | sudo debconf-communicate
            #dpkg-reconfigure man-db < /dev/null || true
            echo "path-exclude=/usr/share/doc/*" >>/etc/dpkg/dpkg.cfg.d/meddle
            echo "path-exclude=/usr/share/man/*" >>/etc/dpkg/dpkg.cfg.d/meddle

            apt-get update
            apt-get install -y python3-django
          EOF

          sudo umount "${base}/etc/_"
          sudo umount "${base}/usr/_"
          sudo umount "${base}/varlib/_"

          sudo rsync -a "${base}/varlib/upper/" /var/lib
          sudo rsync -a "${base}/usr/upper/" /usr
          sudo rsync -a "${base}/etc/upper/" /etc

          # Did it make it to the host?
          dpkg -l python3-django
          dpkg --verify python3-django


          # docker container export ...
          # extract /etc, /usr, and specific /var paths like /var/lib/dpkg
