name: 📦 FPM - Multiple Platforms
run-name: 📦 FPM - Multiple Platforms (v${{ inputs.version }})

on:
  workflow_dispatch:
    inputs:
      version: 
        default: "1.16.0"
        description: The version of FPM to package

env:
  registry: ghcr.io

jobs:
  package:
    name: 📦 FPM v${{ matrix.version }} for ${{ matrix.image }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: 
          - ${{ inputs.version }}
        image:
          - "debian:11"
          - "debian:12"
          - "fedora:42"
          - "rockylinux/rockylinux:9"
          - "rockylinux/rockylinux:10"
          - "ubuntu:22.04"
          - "ubuntu:24.04"
          - "almalinux:9"
          - "almalinux:10"
          - "amazonlinux:2023"

    env:
      # docker/build-push-action is documented to output an 'imageid', but in
      # practice, it seems to only output 'metadata' and nothing else
      # So, in order to know what docker image we just built, we gotta name it with a tag.
      # Reference: https://github.com/docker/build-push-action/issues/1209
      TARGET_TAG: "lolcomputers"

      # Disable docker/build-push-action's summary output
      # Reference: https://github.com/docker/build-push-action?tab=readme-ov-file#environment-variables
      DOCKER_BUILD_SUMMARY: false

      # This job doesn't publish the docker image so there's no need for any kind of record uploading
      DOCKER_BUILD_RECORD_UPLOAD: false

    outputs:
      files: ${{ steps.package.outputs.files }}
      system_id: ${{ steps.package.outputs.system_id }}
      system_version: ${{ steps.package.outputs.system_version }}
      #artifact_id: ${{ steps.upload.outputs.artifact-id }}
      #artifact_url: ${{ steps.upload.outputs.artifact-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build apt/dnf-ready docker image
        uses: docker/build-push-action@v6
        with:
          context: fpm
          outputs: type=docker # Write image to local docker cache
          tags: ${{ env.TARGET_TAG }}-prepare
          target: prepare # the docker stage to build
          build-args: |
            IMAGE=${{ matrix.image }}
            FPM_VERSION=${{ matrix.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Package fpm
        id: build
        uses: docker/build-push-action@v6
        with:
          context: fpm
          outputs: type=docker # Write image to local docker cache
          tags: ${{ env.TARGET_TAG }}
          build-args: |
            IMAGE=${{ matrix.image }}
            FPM_VERSION=${{ matrix.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Grab package file
        id: package
        run: |
          # Extract content from the docker image built in the previous step
          #docker run ${{ env.TARGET_TAG }} sh -c 'cd target; tar -zc *' | tar -zvx | tee files

          # Some images don't have 'tar' by default, so let's copy files across bind mounts.
          docker run --user="$(id -u):$(id -g)" \
            --volume "./:/out:z" "$2" \
            sh -c "cp /tmp/target/* /out; (cd /tmp/target; find .)" - | tee files

          echo "files<<FILES" >> $GITHUB_OUTPUT
          cat files >> $GITHUB_OUTPUT
          echo "FILES" >> $GITHUB_OUTPUT
          echo "package=$(egrep '\.(deb|rpm)$' files)" >> $GITHUB_OUTPUT

          # Use distro-version as the artifact name
          echo "artifact-name=$(jq -r '"\(.distro)-\(.version)"' package.json)" >> $GITHUB_OUTPUT
          
      - name: "Verify package works"
        run: |
          docker run \
            --volume=./fpm/verify.sh:/work/verify.sh:z \
            --volume="./${{ steps.package.outputs.package }}:/work/${{ steps.package.outputs.package }}:z" \
            --workdir=/work \
            ${{ env.TARGET_TAG }}-prepare sh verify.sh "${{ steps.package.outputs.package }}"

      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.artifact-name }}
          path: |
            ${{ steps.package.outputs.files }}

  check-artifacts:
    name: 📦 Checking Artifacts
    runs-on: ubuntu-latest
    needs: [ package ]

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: List
        run: |
          echo "# Artifacts" >> $GITHUB_STEP_SUMMARY
          find artifacts  | sed -e 's/^/* /' >> $GITHUB_STEP_SUMMARY

          for i in artifacts/*/package.json ; do
            echo $i
            jq < $i
            echo
          done

  publish:
    name: "🚢 Publish Packages"
    needs: [ package, "check-artifacts" ]
    uses: ./.github/workflows/publish-package.yml
    permissions:
      contents: write
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}