name: Package FPM via docker

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 1.16.0 ]
        image: [ "rockylinux:9", "fedora:42", "ubuntu:24.04" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Package fpm with fpm :)"
        id: package
        run: |
          outdir="packages/${{ matrix.image }}/"
          docker run -it --workdir /tmp \
            --volume=""./fpm/build.sh:/tmp/build.sh:z" \
            --volume="./${outdir}:/tmp/target:z" \
            debian:latest sh /tmp/build.sh all
          
          echo "files=<<FILES" >> $GITHUB_OUTPUT
          find "${outdir}" >> $GITHUB_OUTPUT
          echo "FILES"  >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.image}}
          path: ${{ steps.package.outputs.files }}