name: Package FPM

on:
  workflow_dispatch:

jobs:
  package:
    strategy:
      matrix:
        version: [ 1.16.0 ]
        ruby_version: [ "3.4.5" ] 
        os: [ "ubuntu-latest" ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Download Ruby
        uses: actions/download-artifact@v4
        with:
          name: ruby-${{ matrix.ruby_version }}.tar
          github-token: ${{ github.token }}
          # https://github.com/jordansissel/actions-experiments/actions/runs/16853055726
          run-id: 16853055726

      - name: Extract Ruby
        run: |
          echo "Unpacking ruby ${{ matrix.ruby_version }} into /"
          sudo tar -C / -xf ruby-${{ matrix.ruby_version }}.tar
          rm ruby-${{ matrix.ruby_version }}.tar

      - name: Install FPM
        run: |
          export PATH="/opt/ruby/${{ matrix.ruby_version }}/bin:${PATH}"
          gem install fpm -v ${{ matrix.version }} --no-document

      - name: Package
        id: package
        run: |
          # Create an entrypoint
          (
            echo "#!/bin/sh"
            echo "exec /opt/ruby/${{ matrix.ruby_version }}/bin/fpm \"\$@\""
          ) > fpm.sh

          chmod 755 fpm.sh

          export PATH="/opt/ruby/${{ matrix.ruby_version }}/bin:${PATH}"

          outdir="build/${{ matrix.os }}"
          mkdir -p "${outdir}"

          # Ruby requires libyaml, zlib, libcrypt, and libgmp
          # fpm requires binutils for `ar`
          fpm -s dir -t deb \
            -p "${outdir}" \
            -n fpm -v "${{ matrix.version }}" \
            --depends libyaml-0-2 \
            --depends zlib1g \
            --depends libcrypt1 \
            --depends libgmp10 \
            --depends binutils \
            /opt/ruby/${{ matrix.ruby_version }}/ fpm.sh=/usr/bin/fpm

          echo "outdir=${outdir}" >> $GITHUB_OUTPUT
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.os }}
          path: ${{ steps.package.outputs.outdir }}

  publish:
    uses: ./.github/workflows/publish-packages.yml