name: Package FPM via docker

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 1.16.0 ]
        image: [ "rockylinux:9", "rockylinux:10", "fedora:42", "ubuntu:24.04", "ubuntu:22.04", "debian:11", "debian:12" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Package fpm with fpm :)"
        id: package
        run: |
          target="${{ matrix.image }}"
          # replace image:tag with image-tag
          # this lets us use the image-tag text as part of a docker --volume value
          target="${target/:/-}" 

          outdir="packages/$target"

          docker run --workdir /tmp \
            --volume="./fpm/build.sh:/tmp/build.sh:z" \
            --volume="./${outdir}:/tmp/target:z" \
            ${{ matrix.image }} sh -x /tmp/build.sh all
          
          echo "files<<FILES" >> $GITHUB_OUTPUT
          find "${outdir}" >> $GITHUB_OUTPUT
          echo "FILES"  >> $GITHUB_OUTPUT

          echo "target=$target" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.target }}
          path: ${{ steps.package.outputs.files }}