name: Publish

on:
  workflow_dispatch:
    #inputs:
      #run_id:
        #required: true
        #type: number
  workflow_call:
    #inputs:
      #run_id:
        #required: true
        #type: number

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: my-branch

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y reprepro

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        #with:
          #github-token: ${{ github.token }}
          #run-id: ${{ inputs.run_id }}

      - name: Explore
        run: |
          ls -lR