name: Publish

on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: pages

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y reprepro

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Push
        run: |
          find artifacts -type f -name '*.deb' -print0 | \
            xargs -0tn1 sh -c 'reprepro -Vb repo includedeb any "$1"' -

          # Need to set git user and email
          # Citation> https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add repo
          git commit repo -m "reprepro packages"
          git push
