name: Publish

on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: pages

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y reprepro

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Push
        run: |
          find artifacts -type f -name '*.deb' -print0 | \
            xargs -0tn1 sh -c 'reprepro -Vb repo includedeb any "$1"' -

          git add repo
          git commit repo -m "reprepro packages"
          git push
