name: Test action secrets

on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: maybe
      uses: ./.github/actions/publish-packages