name: Test action secrets

on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: maybe
      uses: ./.github/action/publish-packages
      with:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}